apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: ds
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: DaemonSet
  placement:
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
    clusterAffinity:
      clusterNames:
        - host
        - member1