apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tools
  labels:
    app: tools
spec:
  selector:
    matchLabels:
      app: tools
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
      - name: tools
        image: ghcr.io/liangyuanpeng/ubuntu:tools-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: HOST_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - sh
        - -c
        - |
          sleep 99h