version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
  ignore:
  - dependency-name: "*"
    update-types: 
    - version-update:semver-minor
    - version-update:semver-patch