name: image-scanning
on:
  push:
    branches:
      - master
  pull_request:
    # branches:
    #   - master
jobs:

  checklabels:
    name: image-scanning
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      areaSecurity: ${{ steps.checklabels.outputs.security }}
    steps:
      - name: checklabels 
        id: checklabels
        env: 
          GHEVENT: ${{ toJSON(github.event) }}
        run: |
          echo  $GHEVENT | jq .
          if echo "${{ github.event.pull_request.labels }}" | grep -q "area/security"; then
            echo "Label exists"
            echo "Run CI tasks here"
            echo "security=true" >> "$GITHUB_OUTPUT"
          else
            echo "Label does not exist"
          fi

  use-trivy-to-scan-image:
    needs: checklabels
    if: needs.checklabels.outputs.security == 'true'
    name: image-scanning
    # if: ${{ github.repository == 'karmada-io/karmada' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - karmada-controller-manager
          - karmada-scheduler
          - karmada-descheduler
          - karmada-webhook
          - karmada-agent
          - karmada-scheduler-estimator
          - karmada-interpreter-webhook-example
          - karmada-aggregated-apiserver
          - karmada-search
          - karmada-operator
          - karmada-metrics-adapter
    steps:
      - name: checkout code
        id: checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # We need to guess version via git tags.
          fetch-depth: 1
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.11
      - name: Build an image from Dockerfile
        run: |
          export VERSION="latest"
          export REGISTRY="docker.io/gcslyp"
          make image-${{ matrix.target }}
      - name: Run Trivy vulnerability scanner
        if: ${{ github.event_name == 'push' }}
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: 'docker.io/gcslyp/${{ matrix.target }}:latest'
          format: 'sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ github.event_name == 'push' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      - name: display scan results
        if: ${{ github.event_name == 'pull_request' }}
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: 'docker.io/karmada/${{ matrix.target }}:latest'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
