name: comments

on:
  issue_comment:
    types: [created]

jobs:

  discussion_event:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: oras-project/setup-oras@v1
        with:
          version: 1.0.0

      - name: run discussion event
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_COMMENT: ${{ github.event.comment.body }}
          PR_NUM: ${{ github.event.issue.number }}
        run: |
          env
          oras pull ghcr.io/liangyuanpeng/files:retestsh
          cat retest.sh
          chmod +x ./retest.sh
          ./retest.sh