name: released image to DockerHub
on:
  release:
    types:
      - published
  push:
    branches:
      - cosign

jobs:
  publish-image-to-dockerhub:
    name: publish to DockerHub
    strategy:
      matrix:
        target:
          - karmada-controller-manager
          - karmada-scheduler
          - karmada-descheduler
          - karmada-webhook
          - karmada-agent
          - karmada-scheduler-estimator
          - karmada-interpreter-webhook-example
          - karmada-aggregated-apiserver
          - karmada-search
          - karmada-operator
    runs-on: ubuntu-20.04
    permissions:
      id-token: write # To be able to get OIDC ID token to sign images.
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # fetch-depth:
          # 0 indicates all history for all branches and tags.
          # for `git describe --tags` in Makefile.
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: install QEMU
        uses: docker/setup-qemu-action@v2
      - name: install Buildx
        uses: docker/setup-buildx-action@v2
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: build and publish images
        env:
          REGISTRY: lypgcs
          VERSION: ${{ github.ref_name }}
          GH_SHA: ${{ github.sha }}
          GH_RUN_ID: ${{ github.run_id }}
          GH_RUN_ATTEMPT: ${{ github.run_attempt }}
          COSIGN_EXPERIMENTAL: 1
        run: make mp-image-${{ matrix.target }}
