name: latest image to DockerHub
on:
  push:
    branches:
      - master
      - reusable_workflow_images
jobs:
  publish-image-to-dockerhub:
    name: publish to DockerHub
    uses: ./.github/actions/build-publish-image.yml
    with:
      username: ${{ secrets.DOCKERHUB_USER_NAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      registry: docker.io/lypgcs